"""
Copilot Tools for GreenMind AI.
Provides direct access to live application telemetry, predictions,
cost and carbon analytics, recommendations, health metrics, and digital twin simulation.
All tools return real structured application data.
"""

from __future__ import annotations

from typing import Any
from ..cloud import get_provider
from ..database import get_telemetry_history
from ..ml import predictor
from ..decision_engine import right_size, scaling_advice
from ..digital_twin.simulator import simulator as dt_simulator
from ..digital_twin.schemas import SimulationScenarioRequest, StateSnapshot
from ..carbon import get_carbon_intensity, available_regions


def get_cloud_metrics(provider: str = "aws", region: str = "us-east") -> dict[str, Any]:
    """Retrieve current cloud metrics (CPU, Memory, Storage, Network, Cost, Carbon)."""
    p = get_provider(provider)
    return p.get_metrics(region)


def get_history(limit: int = 50) -> list[dict[str, Any]]:
    """Retrieve historical telemetry entries from the ring buffer/database."""
    return get_telemetry_history(limit)


def get_predictions(cpu: float | None = None, hour: float | None = None) -> dict[str, Any]:
    """Retrieve ML forecasts across all 5 dimensions (CPU, memory, network, cost, carbon)."""
    from datetime import datetime, timezone
    now = datetime.now(timezone.utc)
    curr_hour = hour if hour is not None else (now.hour + now.minute / 60.0)
    day = now.weekday()

    if cpu is None:
        metrics = get_cloud_metrics("aws", "us-east")
        cpu = metrics.get("cpu", 45.0)

    forecasts = predictor.predict_all(
        cpu=cpu,
        memory=52.0,
        network=450.0,
        cost_usd=0.192,
        carbon_intensity=210.0,
        hour=curr_hour,
        day_of_week=day,
    )
    return {
        dim: {
            "current": f.current,
            "predicted": f.predicted,
            "delta_pct": f.delta_pct,
            "anomaly": f.anomaly,
            "confidence": f.confidence,
        }
        for dim, f in forecasts.items()
    }


def get_cost_analysis(days: int = 7) -> dict[str, Any]:
    """Retrieve cost optimization analysis, spend breakdown, and top cost drivers."""
    from ..routers.analytics import cost_analytics
    res = cost_analytics(days=days)
    return res.model_dump()


def get_carbon_analysis(days: int = 7, region: str = "us-east") -> dict[str, Any]:
    """Retrieve carbon intensity analysis, clean energy window, and emissions breakdown."""
    from ..routers.analytics import carbon_analytics
    res = carbon_analytics(days=days, region=region)
    return res.model_dump()


def get_recommendations(provider: str = "aws", region: str = "us-east") -> list[dict[str, Any]]:
    """Retrieve active optimization recommendations generated by the multi-agent system."""
    from ..routers.recommendations import _build_recommendations
    recs, score = _build_recommendations(provider, region)
    return [r.model_dump() for r in recs]


def get_cloud_health(provider: str = "aws", region: str = "us-east") -> dict[str, Any]:
    """Retrieve overall infrastructure health indicators and optimization scores."""
    p = get_provider(provider)
    health = p.get_health(region)
    from ..routers.analytics import optimization_scores
    scores = optimization_scores(provider=provider, region=region)
    health["optimization_scores"] = scores.model_dump()
    return health


def run_digital_twin_simulation(
    scenario: str = "RIGHT_SIZE",
    cpu: float = 80.0,
    cost: float = 1000.0,
    carbon: float = 6.2,
) -> dict[str, Any]:
    """Run non-destructive digital twin simulation for a given scenario."""
    req = SimulationScenarioRequest(
        scenario=scenario,  # type: ignore
        current_state=StateSnapshot(
            cpu=cpu,
            cost=cost,
            carbon=carbon,
            monthly_cost=cost,
            monthly_carbon_kg=carbon,
        ),
    )
    res = dt_simulator.run_simulation(req)
    return res.model_dump()
